### PR TITLE
Mark classes used by s4sdk as API

### PR DESCRIPTION
**Pull request by fwilhe**

### CODE REVIEW

**Comment by fwilhe** [comment]
Hello @marcusholl, a review would be appreciated.

**Review by marcusholl — COMMENTED** [review]
* Changes in README.md --> ok
* Changes in ConfigHelper --> ok
* ConfigLoader, ConfigMerger, DefaultValueCache, JenkinsUtils --> In my mind they are only used either inside steps or inside ConfigHelper. Would be interesting to know the use case why they need to appear in a pipeline. The root cause why I'm asking: I think we should keep the API small in order to stay flexible. There must be a really good reason for making something API.
* ContainerMap I cannot say anything.

**Comment by fwilhe** [comment]
My understanding of the agreement was that we check which (implicit) API we currently use, and mark this as `@API` so that it is transparent. Our usage of those clases can be tracked in the [GitHub search](https://github.com/SAP/cloud-s4-sdk-pipeline-lib/search?q=com.sap.piper).

This is the current state, and I can't commit to us not using those classes.

**Comment by marcusholl** [comment]
@fwilhe : please cross check the piper lib itself. We do not make use of `ConfigurationMerger` / `ConfigurationLoader` in the steps. This all is encapsulated inside `ConfigurationHelper`.

Should be possible on your side also. Maybe you will say "Well, but changing that on our side means efforts ...". That is true of course. But having a broader API will also increase development efforts in the future. So I would like to ask if it is possible to adjust the code on your side so that you make more use of the `ConfigurationHelper`.

**Comment by fwilhe** [comment]
@marcusholl Please have another look here after our discussion

**Pull request merged**
